### ISSUE TITLE
401 Errors

### ISSUE THREAD

**Issue by ryenshaie1** [libresec/duo_log_grabber#6]
Hello,

I have updated the conf.ini file with the integration key, secret key, and API host; have installed the dependencies in the requirements.txt file (duo_client and loggerglue), but I am still getting 401 error codes for authentication errors. Any insight?

Thank you!

Ryan

**Comment by libresec** [comment]
Hi Ryan,

The most likely culprit is that your api account is set up incorrectly. Go to "Dashboard --> Account" in the Duo admin console and confirm the type is Admin API. Let me know if that works for you.

--Joe

**Comment by ryenshaie1** [comment]
Thanks Joe, it was indeed because the Admin API was not active. 

A follow-up question for you: we are using Active Directory to import users into Duo and the logs seem to just show "duser=AD" for these entries rather than the individual user. Any insight into this?

Thank you!
-Ryan

**Comment by libresec** [comment]
I'm not sure why that's happening. Can you share a debug file?

**Comment by libresec** [comment]
Forgot to close this back in 2017
